modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="https://minecraftforge.net/"
logoFile="forge_logo.png"
license="LGPL v2.1"

[[mods]]
    modId="forge"
    version="${global.forgeVersion}"
    updateJSONURL="https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
    displayURL="https://minecraftforge.net/"
    displayName="Forge"
    credits="Anyone who has contributed on Github and supports our development"
    authors="LexManos,cpw"
    description='''
    Forge, a broad compatibility API.
    '''
[[mods]]
modId="goldenforge"
version="${global.forgeVersion}"
displayURL="https://goldenforge.modcraftmc.fr"
displayName="GoldenForge"
credits="Anyone who has contributed on Github and supports our development"
authors="manugame"
description='''
    A fork of forge designed to improve modded server performance.
    '''
