name: Goldenforge nightly builds
on:
  push:
    branches:
      - 1.21.1
      - dev/1.21.1/new-patch-system
jobs:
  build:
    runs-on: [self-hosted, goldenforge]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup
        uses: gradle/actions/setup-gradle@v5.0.0
      - name: Clean and setup
        run: ./gradlew clean neoforge:setup
      - name: Apply goldenforge patches
        run: ./gradlew clean goldenforge:setupGoldenForge
      - name: Build jar
        run: ./gradlew goldenforge:installerjar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: goldenforge-1.21.1
          path: projects/goldenforge/build/libs/goldenforge-*-installer.jar